---
title: "Tooth Growth.R"
author: "Harold Trammel"
date: "August 20, 2015"
output: html_document
---
```{r lock_n_load}
data("ToothGrowth")

library(dplyr)
library(ggplot2)
library(knitr)
library(printr)

se <- function(x) sqrt(var(x)/length(x))

tg <- ToothGrowth %>%
    group_by(supp, dose) %>%
    summarise_each(funs(mean, sd, se)) %>%
    rename(tg_mean = mean, tg_sd = sd, tg_se = se)


pl1 <- ggplot(ToothGrowth, aes(factor(dose), y=len, fill = supp)) +
    geom_boxplot(stat="boxplot", outlier.colour = "blue", notch = FALSE) +
    ggtitle("ToothGrowth data: length vs dose, given type of supplement")
print(pl1)


pl2 <- ggplot(ToothGrowth, aes(factor(dose), y=len, fill = supp)) +
    geom_violin(stat="ydensity", position = "dodge") +
    ggtitle("ToothGrowth data: length vs dose, given type of supplement")
print(pl2)


tg_limits <- aes(ymax = tg_mean + tg_se, ymin = tg_mean - tg_se)
pl3 <- ggplot(tg, aes(dose, tg_mean)) +
    geom_point(stat="identity", colour="red", size=3) +
    geom_errorbar( tg_limits, width = 0.1) +
    ggtitle("ToothGrowth data: length vs dose, given type of supplement") +
    facet_grid(.~supp)
print(pl3)

```


# Part Two
Now in the second portion of the class, we're going to analyze the ToothGrowth data in the R datasets package.

1. Load the ToothGrowth data and perform some basic exploratory data analyses
2. Provide a basic summary of the data.
3. Use confidence intervals and/or hypothesis tests to compare tooth growth by supp and dose. (Only use the techniques from class, even if there's other approaches worth considering)
4. State your conclusions and the assumptions needed for your conclusions.

Some criteria that you will be evaluated on

* Did you  perform an exploratory data analysis of at least a single plot or table highlighting basic features of the data?
* Did the student perform some relevant confidence intervals and/or tests?
* Were the results of the tests and/or intervals interpreted in the context of the problem correctly?
* Did the student describe the assumptions needed for their conclusions?


# Purpose for the Study 
According to patched R Reference Manual entry for the Tooth Growth dataset, the citation for the original study from which this data was obtained is Crampton, E. W. (1947) The growth of the odontoblast of the incisor teeth as a criterion of vitamin C intake of the guinea pig. _The Journal of Nutrition_ 33(5): 491–504. [link] (http://jn.nutrition.org/content/33/5/491.full.pdf). In this paper, the authors state the purpose of the study to be the evaluation of odnotoblast growth as a bioassay for vitamin C levels.  The procedures used in the study preclude paired comparisons of the results.
